name: "Cronjob get RSS"
on:
  # schedule:
  #   - cron: '*/30 * * * *'
  push:
    branches:
      - 'main'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in eplus.dev posts
        uses: ePlus-DEV/blog-post-workflow@v1
        with:
          retry_count: 2
          feed_list: "https://raw.githubusercontent.com/hoangsvit/eplus.dev/refs/heads/main/data/rss.xml"
          committer_email: "h250694@gmail.com"
          commit_message: Get blog posts
          rand_seed: "hoangsvit"
          date_format: 'UTC: yyyy-mm-dd'
          template: " $newline - $randomEmoji(💯,🔥,💫,🚀,🌮,📝,🥳,💻,🧰,🏊,🥰,🧐,🤓,😎,🥸,🤩,🤗,🤔,🫣,🤭,🤠,👹,👺,🤡,🤖,🎃,😺,🫶,👍,💪,💄,👀,🧠,🧑‍🏫,👨‍🏫,💂,🧑‍💻,🥷,💃,🕴,💼,🎓,🐻,🐵,🙉,🦄,🦆,🦅,🦍,🦣,🐘,🦒,🦏,🐎,🦩,🐲,🌝,🌜,🌏,🌈,🌊,🎬,🎭,🚀,🚦,⛽️,🗽,🎡,🌋,🌁,💡,🕯,🪜,🧰,⚗️,🔭,🪄,🎊,🎉) [$title]($url) -$date"
          max_post_count: 15
