name: Generate posts.json and feed.rss

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - "scripts/generate-posts-json.js"
      - ".github/workflows/generate-posts-json.yml"

  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  generate-posts-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Generate data/posts.json and feed.rss
        run: node scripts/generate-posts-json.js

      - name: Commit generated files if changed
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            
            git pull
            git add data/posts.json data/rss.xml

            if git diff --cached --quiet; then
            echo "No changes to commit"
            else
            git commit -m "chore: generate posts json and rss xml"
            git push
            fi